import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { useApp } from "../context/AppContext";
import { Heart, ShoppingCart, Trash2, Star } from "lucide-react";
export const WishlistView = () => {
    const { wishlist, products, toggleWishlist, addToCart, setCurrentView, setSelectedProductId } = useApp();
    const wishlistedProducts = products.filter((p) => wishlist.includes(p.id));
    const handleProductClick = (id) => {
        setSelectedProductId(id);
        setCurrentView("product-details");
    };
    if (wishlist.length === 0) {
        return (_jsxs("div", { className: "max-w-md mx-auto px-4 py-20 text-center space-y-4 font-sans", children: [_jsx(Heart, { className: "w-12 h-12 text-rose-300 mx-auto animate-pulse" }), _jsx("h2", { className: "text-xl font-bold text-zinc-800 dark:text-white", children: "Your Wishlist is Empty" }), _jsx("p", { className: "text-xs text-zinc-500", children: "Keep track of your favorite luxury gift hampers and box caskets here." }), _jsx("button", { onClick: () => setCurrentView("shop"), className: "px-5 py-2.5 bg-rose-500 text-white font-bold rounded-xl shadow-md text-xs cursor-pointer", children: "Explore Catalog" })] }));
    }
    return (_jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 font-sans space-y-8 animate-fade-in", children: [_jsx("h1", { className: "text-2xl sm:text-3xl font-extrabold text-zinc-950 dark:text-white tracking-tight", children: "My Wishlist" }), _jsx("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-6", children: wishlistedProducts.map((p) => (_jsxs("div", { className: "bg-white dark:bg-zinc-900 border border-zinc-100 dark:border-zinc-800/80 rounded-3xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 relative flex flex-col h-full group", children: [_jsx("button", { onClick: () => toggleWishlist(p.id), className: "absolute top-3 right-3 p-2 bg-white/95 dark:bg-zinc-900/95 text-rose-500 rounded-full shadow-sm cursor-pointer z-10", title: "Remove from Wishlist", children: _jsx(Trash2, { className: "w-4 h-4" }) }), _jsx("div", { onClick: () => handleProductClick(p.id), className: "aspect-square overflow-hidden cursor-pointer bg-zinc-50", children: _jsx("img", { src: p.image, alt: p.name, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" }) }), _jsxs("div", { className: "p-4 flex flex-col flex-1 gap-2", children: [_jsx("span", { className: "text-[10px] font-bold text-zinc-400 uppercase tracking-widest", children: p.category }), _jsx("h3", { onClick: () => handleProductClick(p.id), className: "text-sm font-semibold text-zinc-900 dark:text-white line-clamp-1 group-hover:text-rose-500 cursor-pointer", children: p.name }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx("div", { className: "flex text-amber-400", children: [...Array(5)].map((_, i) => (_jsx(Star, { className: `w-3 h-3 ${i < Math.floor(p.rating) ? "fill-amber-400" : "text-zinc-200"}` }, i))) }), _jsxs("span", { className: "text-[10px] text-zinc-400", children: ["(", p.reviewsCount, ")"] })] }), _jsxs("div", { className: "flex items-center justify-between mt-auto pt-2 border-t border-zinc-100 dark:border-zinc-800", children: [_jsxs("span", { className: "text-sm font-bold text-zinc-900 dark:text-white font-mono", children: ["$", p.price] }), _jsx("button", { onClick: () => addToCart(p, 1), className: "p-2 bg-rose-50 text-rose-600 hover:bg-rose-500 hover:text-white rounded-lg transition-all", title: "Move to Cart", children: _jsx(ShoppingCart, { className: "w-4 h-4" }) })] })] })] }, p.id))) })] }));
};
